### ISSUE TITLE
On-boarding

### ISSUE THREAD

**Issue by ltartari** [godunno/dunno#676]
## To-do
- [x] Remove old tutorial assets, markup and style. #675 
- [x] Copy for onboarding
- [ ] Place copy into code
- [ ] Implement element highlight
- [ ] Mark onboarding as done for each element/step of the way
- [ ] Remove old tutorial implementation.
